### ISSUE TITLE
mail.ru — #$?# { remove: true; }' don't work correctly

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/ExtendedCss#100]
Open main page `mail.ru` and scroll some times after Pulse column. 
Elements don't load correctly and on this tab I got high cpu usage. Without `#$?# { remove: true; }` it works fine.
Rule `mail.ru,~auto.mail.ru,~cloud.mail.ru,~e.mail.ru,~esports.mail.ru,~games.mail.ru,~go.mail.ru,~health.mail.ru,~hi-tech.mail.ru,~horo.mail.ru,~kino.mail.ru,~lady.mail.ru,~love.mail.ru,~mailblog.mail.ru,~minigames.mail.ru,~my.mail.ru,~news.mail.ru,~otvet.mail.ru,~pogoda.mail.ru,~realty.mail.ru,~touch.mail.ru,~tv.mail.ru#$?#.pulse-lenta > div > div > div[class*="_"]:has(> div > a[href^="https://t.mail.ru/redir/"]) { remove: true; }`

<details><summary>issue:</summary>

![image](https://user-images.githubusercontent.com/33488229/74141260-a5e5bc00-4c07-11ea-9974-425ce780ad71.png)
</details><br/>

**Comment by ameshkov** [comment]
Well, it just means you should not use that rule because it messes with their JS
