### ISSUE TITLE
Rules with insensitive attribute don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/ExtendedCss#104]
It seems that rules with insensitive attribute don't work.
For example:
`adguard.com#?#body:has(div[class="page" i])`
or
`adguard.com#?#div[class="page" i]`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/76771874-49466580-67a0-11ea-8c35-35b8669b3b47.png)

</details>

<hr>

Rule like this:
`adguard.com##body div[class="page" i]`
or
`adguard.com##div[class="page" i]`
works fine.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/76772040-890d4d00-67a0-11ea-8e08-799596c57cb4.png)

</details>

**Comment by slavaleleka** [comment]
Sizzle does not support case-insensitive attribute so we can not fix it with ease now

**Comment by slavaleleka** [comment]
merged into https://github.com/AdguardTeam/ExtendedCss/issues/110

**Comment by ameshkov** [comment]
Let’s reopen it and implement at least a temporary solution. At least we could discard these rules.
