### ISSUE TITLE
Problem loading script extended-css.js

### ISSUE THREAD

**Issue by WrongBit** [AdguardTeam/ExtendedCss#105]
I load it in Opera 67 (on Win7x64). Opera gives error:

> Cannot use import statement outside a module

I load it using console and script:

`!function(E,x,t,C,s,s_){C=E.createElement(x),s=E.getElementsByTagName(x)[0],C.src=t,
C.onload=function(){alert('ExtCss loaded successfully')},s.parentNode.insertBefore(C,s)}
(document,'script','http://127.0.0.1/ext.js')
`

**Comment by ameshkov** [comment]
It seems that the dev build is outdated, we'll see what can be done about it.
