### ISSUE TITLE
Some :xpath rules don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/ExtendedCss#106]
For example rule like this doesn't work:
```
ghacks.net#$?#:xpath(//div[@class="user-content"]/div[@class="snippet-clear"]/following-sibling::text()[contains(.,'Advertisement')]) { remove: true; }
```
or
```
ghacks.net#?#:xpath(//div[@class="user-content"]/div[@class="snippet-clear"]/following-sibling::text()[contains(.,'Advertisement')])
```

It should remove "Advertisement" text in this article - https://www.ghacks.net/2020/04/22/vivaldi-3-0-with-adblocker-and-tracker-blocker-released/

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/80137135-182d3200-85a3-11ea-96ab-20bd39d539eb.png)

</details>

Something like this works:

```
var el = document.evaluate( `//div[@class="user-content"]/div[@class="snippet-clear"]/following-sibling::text()[contains(.,'Advertisement')]`, document, null, XPathResult.ANY_TYPE, null ).iterateNext();

el.remove();
```

so I think it should be possible.

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/80137208-37c45a80-85a3-11ea-96d2-19d69c611b77.png)

![image](https://user-images.githubusercontent.com/29142494/80137262-4a3e9400-85a3-11ea-9eed-36ef190a475b.png)

![image](https://user-images.githubusercontent.com/29142494/80137296-5aef0a00-85a3-11ea-8ef9-57b9e30dd170.png)

</details>

**Comment by ameshkov** [comment]
@slavaleleka fixing this would be on you after we finish with scriptlets

**Comment by slavaleleka** [comment]
we should get back to this task when we replace Sizzle

**Comment by slavaleleka** [comment]
merged into https://github.com/AdguardTeam/ExtendedCss/issues/110

**Comment by slavaleleka** [comment]
Related: https://github.com/AdguardTeam/ExtendedCss/issues/144
