### ISSUE TITLE
`:contains` rule with the dot breaks the sites

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExtendedCss#107]
`#$#*:contains(/text./) { display: block; }`
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/80525772-6b83f380-899a-11ea-97ea-b319cdc10d4b.png)

</details>

**Comment by ameshkov** [comment]
Please check what is responsible - CoreLibs or ExtCSS

**Comment by slavaleleka** [comment]
ExtCSS is responsible for this, and this is not a bug

because `:contains()` pseudo-class uses `textContent` element property for matching. and as long as textContent property of `head` element contains `text`, the rule will match it and make it visible
