### ISSUE TITLE
Add support for :remove() 

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/ExtendedCss#108]
For example this rule:
`example.org##body:remove()`
should works the same as:
`example.org#$?#body { remove: true; }`

Example link - http://example.org/

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#subjectremove

**Comment by ameshkov** [comment]
We should simply convert :remove() to `{ remove: true; }` automatically.

**Comment by ameshkov** [comment]
It does not matter. Conversion is being done in the ExtendedCSS constructor and at this point you'll be dealing with something like `body:remove() { display: none; }` which you should convert to `body { remove: true, display: none }`
