### ISSUE TITLE
Remake :upward() after Sizzle replacement 

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/ExtendedCss#111]
>Limited to work properly only at the end of selector, except of pseudo-class :remove().

What is the reason of this limitation?
I mean that in third party filters there are few rules like this `#?#selector:upward(1) + anotherSelector`, so these rules will not work.

For example in Swedish filter:
```
tidningen.nu##span:has-text(/^Annons$/):upward(1) + .textwidget
viafree.se##.vjs-playing:upward(1) ~ .no-autoplay-overlay
```
https://github.com/AdguardTeam/FiltersRegistry/blob/6cce7c92672856220f256e85a26a2494196e35c3/filters/ThirdParty/filter_243_FrellwitSwedish/diff.txt#L200

_Originally posted by @AdamWr in https://github.com/AdguardTeam/ExtendedCss/issues/102#issuecomment-668677818_

**Comment by slavaleleka** [comment]
merged into https://github.com/AdguardTeam/ExtendedCss/issues/110

**Comment by krystian3w** [comment]
I have another one idea with upward:

`mail.yahoo.com#$#div[data-test-id="efv-subheader"]:has(:upward(1) ~ div[data-test-id="video-container"])`

and this is needed for AdGuard only:


`mail.yahoo.com#?#div[data-test-id="efv-header"]:has(~ div[data-test-id="video-container"]) > div[data-test-id="efv-subheader"]`
