### ISSUE TITLE
Combined style and ExtendedCss no work when found "\" in pseudo-class with uBO syntax 1.29.3b10+

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/ExtendedCss#114]
I try hide newsletter leftover on site `telewizja-cyfrowa.com` in right column (sidebar):

<details> <summary> screenshot </summary><br>

![obraz](https://user-images.githubusercontent.com/35370833/92507180-dd046600-f206-11ea-9d4c-b9f135b3a03a.png) |
--- |
`https://telewizja-cyfrowa.com/` |

</details>

by:

```
telewizja-cyfrowa.com###text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/):style(font-size: 0 !important;)
```

And filter does not work in AdGuard Addon and I suppose is no translated correct in FiltersRegistry:

> https://github.com/AdguardTeam/FiltersRegistry/commit/9dafde297a9a9dd6fadbc89cf854057e36d540e2#diff-aadf84ddda58c6ad55b8ceb5f0e975b3

For works is needed mark as ExtendedCSS manually:

```
telewizja-cyfrowa.com#?##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/):style(font-size: 0 !important;)
```

But uBO no need this in own syntax.

---

related: https://github.com/AdguardTeam/FiltersRegistry/issues/381

**Comment by krystian3w** [comment]
OK, I suppose glitch by `:has-text(/[\w\W]{337}/)` or `:has-text(/wiadomosci\./)` = "`\`".

**Comment by slavaleleka** [comment]
@krystian3w 
is it possible to use `:style(...)` in ubo-whitelist rules

**Comment by krystian3w** [comment]
Yes by `#@#` / and `#@$#` :

```
telewizja-cyfrowa.com#@##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/):style(font-size: 0 !important;)`
```
```
telewizja-cyfrowa.com#@$##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/) { font-size: 0 !important; }
```


---


![obraz](https://user-images.githubusercontent.com/35370833/93104957-c64e8b00-f6ae-11ea-80da-1606ab1776c6.png)  |
--- |
red overlay is False Positive to fix in CodeMirror HighLighter. |

**Comment by krystian3w** [comment]
Yes by `#@#` (unless I misunderstood):

```
telewizja-cyfrowa.com#@##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/):style(font-size: 0 !important;)
```

Also cover whitelist by:

* `#@$#`  with `:has(foo)` and `{ foo }` 
* `#@$?#` with `:has(foo)` and `{ foo }` 

AdGuard Base demo

```diff
! https://github.com/AdguardTeam/AdguardFilters/issues/44442
sadeempc.com#$?#body[style*="visibility"] { visibility: visible!important; }
```

* `sadeempc.com#@$#body[style*="visibility"] { visibility: visible!important; }` 
   -  disable specific css

* `sadeempc.com#@$?#body[style*="visibility"] { visibility: visible!important; }`
    - disable specific css



---

but my whitelist filter is marked as no supported / invalid:

![obraz](https://user-images.githubusercontent.com/35370833/93104957-c64e8b00-f6ae-11ea-80da-1606ab1776c6.png)  |
--- |

```
telewizja-cyfrowa.com#@$##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/) { font-size: 0 !important; }
telewizja-cyfrowa.com#@$?##text-2 > .textwidget > p:nth-of-type(1):has-text(/[\w\W]{337}/):has-text(/Dołącz/) { font-size: 0 !important; }
```

IMO also by "\" https://github.com/AdguardTeam/ExtendedCss/issues/114#issuecomment-690894524

---

**Comment by slavaleleka** [comment]
Issue moved to [AdguardTeam/AdguardBrowserExtension #1702](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1702) via [**ZenHub**](https://www.zenhub.com/)
