### ISSUE TITLE
Ext-CSS rules don't apply in apps at hotcleaner.com

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/ExtendedCss#127]
@Sergey-Lyapin commented on [Fri Apr 09 2021](https://github.com/AdguardTeam/CoreLibs/issues/1435)

Ext-CSS rules don't apply in apps at hotcleaner.com (from user rules as well)

Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/79709

![Screenshot 2021-04-09 at 13 38 21](https://user-images.githubusercontent.com/18536328/114171393-e7bddf80-993c-11eb-82fb-309f13407736.png)

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/ExtendedCss/issues/160
