### ISSUE TITLE
Attribute display: none !important; is removed after few seconds

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExtendedCss#13]
Example link:
https://yandex.ru/pogoda/odessa/
Rules:

```
##.navigation-city_js_inited[-ext-has='a[onmousedown*="clck.yandex."]']
##.info__map[-ext-has='div[class]:contains(Яндекс.Директ)']
```

**Comment by Alex-302** [comment]
The second example:
http://www.softpedia.com/
Rule:
```
softpedia.com#$#div[style^="font-size:"][style$="font-weight: 500;"][-ext-contains="Advertisement"] { position: absolute!important; left: -2000px!important; }
```
or
```
softpedia.com##div[style^="font-size:"][style$="font-weight: 500;"][-ext-contains="Advertisement"]
```
<details>
![image](http://imagizer.imageshack.com/img923/1633/gsXdTh.png)
</details>
While loading the rule works
<details>
![image](http://imagizer.imageshack.com/img924/7139/xZnpCV.png)
</details>
After loading custom attributes are reseted:
<details>
![image](http://imagizer.imageshack.com/img923/3478/xn6XeW.png)
</details>
CSS rule works as expected:
```
##div[style^="font-size:"][style$="font-weight: 500;"]
```

**Comment by Alex-302** [comment]
Another one #14

**Comment by ameshkov** [comment]
Done

**Comment by seanl-adg** [comment]
It is not working on `4pda.ru`. Repro steps: add `4pda.ru##article.post:has(> .visual > a[title=Honor])
`. The very first implementation had a flaw https://github.com/adguardteam/ExtendedCss/commit/a368ab4f29ecbfe46cb77f61bc7a0f1983829533#diff-1972c050c1317f95f4490c0e2e7313f2R55

**Comment by ameshkov** [comment]
Assigned to 1.0.11 milestone.
