### ISSUE TITLE
Not ordinary behavior pseudo-class :remove() with :upward()

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/ExtendedCss#131]
@XX-J commented on [Thu Jun 03 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1817)

Если применить правило `example.com##a:upward(div):remove()`, то элемент **скроется**, а не удалится.

<details><summary>Screenshot:</summary>

![2021 06 01-2](https://user-images.githubusercontent.com/17948007/120580379-c4da1400-c431-11eb-867c-3f179423ce4b.png)
</details>
<br>

 А если такое: `example.com#$#a:upward(div) { remove: true; }`, то удалится.

<details><summary>Screenshot:</summary>

![2021 06 02-1](https://user-images.githubusercontent.com/17948007/120580722-547fc280-c432-11eb-81c5-da18f0994296.png)
</details>
<br>

Удаляться должен в обоих случаях.

[https://example.com](https://example.com)

**Comment by XX-J** [comment]
Заработало, спасибо.
 Можно закрывать.
