### ISSUE TITLE
Detected GPL violation of nagware using your source code

### ISSUE THREAD

**Issue by Exagone313** [AdguardTeam/ExtendedCss#137]
Hello,

I'd like to bring your attention on the project named [Total Adblock](https://www.totaladblock.com/).

This is a product that ships an adblocker that works for a limited time, then asks users to pay for an unlimited version after some use. Their website seems to say that it works for no charge during 7 days, but comments on AMO shows it blocks usage of it after a few hours of usage and shows advertisements nagging users to buy their software (I haven't looked at their minified code). So basically, this is called a nagware.

I downloaded their Firefox extension's xpi on AMO: https://addons.mozilla.org/en-US/firefox/addon/total-adblock/
```
dafc3a5e55b0a0d53e403b282afb8446aafb09e7004d84e187b8888b33cd68b2  ../total_adblock_ad_blocker-2.8.0-fx.xpi
```

I can provide the file if requested, I just don't know where to host it.

Note: it probably bought reviews or generated these automatically, since it has so many good reviews.

The extension ships code that comes from this repository, in the file `adguard/adguard-content.js` at line 254:
```
/*! extended-css - v1.3.13 - Thu Jul 29 2021
* https://github.com/AdguardTeam/ExtendedCss
* Copyright (c) 2021 AdGuard. Licensed GPL-3.0
*/
var ExtendedCss = (function () {
  'use strict';
```

**The extension is not GPL-licensed as a whole**, they have not released their source code, only minified code is available. AMO says: 
```
License
    All Rights Reserved
```

It also includes source code under LGPLv3 and Apache 2.0, from your main repository, for example in that very same file:
```
/**
 * This file is part of Adguard Browser Extension (https://github.com/AdguardTeam/AdguardBrowserExtension).
 *
 * Adguard Browser Extension is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
```

It also includes a list of many content blocking lists like EasyList, like any other content/ad blocker.

---

**While I am not a copyright holder of your code, I'm very sad to see nagware using free software code without at least doing it right: whole code must be GPL-ed or compatible with GPL.** This is not the case here.

PS: I have discovered your software through this one.

### Additional information:

They are making ads for their software on YouTube.

Their EULA is copied from another website, maybe a company that works as a proxy, it seems very sketchy:
```
22. 
Protected.net Group Contact information
If you have any questions or comments, please contact us at support@totaladblock.com or postal mail to:
Protected.net LLC trading as Protected (totaladblock),
1501 Main St,
Suite 201,
Venice,
California,
90291,
United States
Protected.net Group Limited trading as Protected (totaladblock),
Larch House,
Parklands Business Park,
Denmead,
Hampshire,
PO7 6XP,
United Kingdom
United States - 833 201 8681
United Kingdom - 0800 357 602
Europe - +44 808 169 7741
Australia - 1800 952 291
Canada - 833 201 8681
International - (001) 833 201 8681
Protected.net Group Limited trading as totaladblock. Company Number 10161957
```

(It also doesn't seem to respect GDPR but that's another story.)

**Comment by Exagone313** [comment]
I'm highlighting you @slavaleleka since you are the maintainer of this software.

**Comment by Exagone313** [comment]
Their other extension is also concerned but I have not analyzed it: https://addons.mozilla.org/en-US/firefox/addon/total-webshield/

**Comment by ameshkov** [comment]
Thank you, we'll check it.
