### ISSUE TITLE
Yandex direct

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/ExtendedCss#14]
Начали [здесь](https://github.com/AdguardTeam/AdguardFilters/issues/2989) разбирать проблему яндекс директа - выяснилось, что правило работает корректно, но скрытое псевдо-классом оно появляется снова или меняет состояние спустя какое-то время.

**Comment by ameshkov** [comment]
А я чот не могу повторить, @Alex-302 в чем там проблема?

Это случаем не то же самое что здесь #13 ?

**Comment by Alex-302** [comment]
@ameshkov сперва реклама скрывается, потом мигает, и пропадает. Через несколько секунд может отобразиться снова. Если покрутить страницу или изменить масштаб она снова появляется; при этих же действиях она может пропасть, если была видимой.
Правила
```
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by#$#.info__map[-ext-has='div[class]:contains(Яндекс.Директ)'] { position: absolute!important; left: -2000px!important; }
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by#$#.navigation-city_js_inited[-ext-has='a[onmousedown*="clck.yandex."]'] { position: absolute!important; left: -2000px!important; }
```

**Comment by ameshkov** [comment]
@Alex-302 повторить все еще не могу, но предполагаю, что причина такая же как и в #13 
Посмотрим как изменится когда мы этот фикс реализуем.

**Comment by Hawkrus** [comment]
Кажется, что на странице яндекса спустя какое-то время отрабатывает скриптик, который не находит рекламку и меняет структуру, чтобы эта рекламка снова появилась. Может надо такие скриптики ловить и вырезать?

**Comment by Alex-302** [comment]
@Hawkrus 
можно ещё раз глянуть?

**Comment by Hawkrus** [comment]
@Alex-302 
223 741 493
891xss

**Comment by Alex-302** [comment]
@ameshkov да, как и #13 - стиль пропадает, а если изменить размер окна снова появляется и баннер пропадает.

**Comment by Alex-302** [comment]
Здесь закрываю, сошлюсь в #13
