### ISSUE TITLE
:not(:has(something)) does not work with ExtCSS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#141]
Check this out: https://github.com/AdguardTeam/AdguardFilters/issues/98560

This rule `ifixit.com##.modalBox:not(:has(.modalContentBox #login))` hides the login modal box while it shouldn't.

We should test this with the new ExtCSS implementation.

**Comment by slavaleleka** [comment]
merged into https://github.com/AdguardTeam/ExtendedCss/issues/110
