### ISSUE TITLE
[Feature request] Support for -abp-properties

### ISSUE THREAD

**Issue by scripthunter7** [AdguardTeam/ExtendedCss#148]
Please consider supporting `-abp-properties`  for better compatibility. 

## TSUrlFilter related example

```typescript
import { RuleFactory } from '@adguard/tsurlfilter';

RuleFactory.createRule("example.com#?#div:-abp-properties(width:300px;height:250px;)", 0);
```
throws
```
Error: "Unknown pseudo class: div:-abp-properties(width:300px;height:250px;)" in the rule: "example.com#?#div:-abp-properties(width:300px;height:250px;)"
```

 ## `-abp-properties` reference: 

https://help.eyeo.com/adblockplus/how-to-write-filters#elemhide-emulation

![image](https://user-images.githubusercontent.com/57285466/182868796-371a576b-cca0-4f88-97b6-5c532c03d0f7.png)

**Comment by slavaleleka** [comment]
AdGuard supported it in past but then [stoped](https://github.com/AdguardTeam/ExtendedCss/issues/93). So I am not sure that we will support it again
