### ISSUE TITLE
Extended CSS rules with `:has()` + `:contains()` do not work in Chrome 105

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/ExtendedCss#149]
Steps to reproduce
1. Install Chrome Beta version 105
2. Add this rule to user rules:
```
example.org#?#div:has(h1:contains(Example))
```
3. Go to - https://example.org/

Website should be blank.

<details><summary>Screenshot (Left Chrome 105, right Chrome 104)</summary>

![image](https://user-images.githubusercontent.com/29142494/185169954-ed2ccbc4-6f9c-42df-b917-1b0d9da7aa58.png)

</details>

**Comment by krystian3w** [comment]
I repoduced on Chrome 106 with uBo dev.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2228 https://github.com/DandelionSprout/adfilt/issues/63

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/127369

https://github.com/AdguardTeam/AdguardFilters/issues/127208

https://github.com/uBlockOrigin/uBlock-issues/issues/2228

https://github.com/AdguardTeam/FiltersRegistry/issues/662
