### ISSUE TITLE
Improve extended CSS performance

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#15]
Sometimes it is really too slow, especially when `:contains` pseudo class is used.
We should improve performance and use `document.querySelectorAll` when possible.

**Comment by Alex-302** [comment]
The following rule causes to lags whyle typing text in search string on the main yandex page 
```
yandex.ru,yandex.ua,yandex.by##.sidebar-panel-view .home-panel-content-view__body   div[style*="!important"][-ext-has="div>a:contains(Яндекс.Директ)"]
```

**Comment by ameshkov** [comment]
@Alex-302 @seanl-adg

The main culprit is complicated selectors looking like `:has(selector:contains(test))`.
Such selectors greatly reduce the overall speed (it could start working 10x or even 20x slower).

**Comment by ameshkov** [comment]
The second issue is how we handle DOM changes. We must throttle extended CSS rules re-applying when DOM is changed dynamically.

**Comment by ameshkov** [comment]
Pull request is on review:
https://github.com/AdguardTeam/ExtendedCss/pull/17

@Alex-302 @seanl-adg
Extended css selectors are now divided into two parts.
Left (simple) part, which could be executed with a standard browser method (querySelectorAll).
Right (complex) part, which is executed using Sizzle css engine.

Simple part allows you to narrow search down to a small amount of nodes, which then will be filtered by Sizzle. However, this could be also a problem if simple part is too "wide" and selects too many elements.

**Do**
`#container .banner > div:has(span)`

It will be divided into `#container .banner` (simple) and `div:has(span)` (complex) parts.

**Don't**
`div span:has(.banner)`

It will be divided into `div` and `span:has(.banner)`. `div` is too wide, so this could even slow selector down.

**Relations**

Simple/complex tokenizer supports simple parenthesis relations (` ` and `>`).
Sibling relations (`~` and `+`) aren't supported, thus it will be considered a part of the "complex" side.

For instance:
`#container .banner + div:has(span)`

Simple part will be `#container`
Complex part will be `.banner + div:has(span)`

**Comment by ameshkov** [comment]
Done
