### ISSUE TITLE
Implement `:matches-css-first-line()` pseudo-class

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/ExtendedCss#150]
DOM elements styled with `:first-line` pseudo-element can not be matched by ExtendedCss for now. We need a new pseudo-class for such cases
https://uploads.adguard.org/slbdzdrvg2pv5.png
https://uploads.adguard.org/slbdzdrvhkdnz.png

> leave in readme a note about how filter-maintainers should check value to match by rule

Related issue:
https://github.com/AdguardTeam/AdguardFilters/issues/126089

**Comment by krystian3w** [comment]
IMO also no possible cover with `:-abp-properties`: https://github.com/AdguardTeam/ExtendedCss/issues/148 (no worth recover support).

**Comment by BlazDT** [comment]
Any news?

**Comment by krystian3w** [comment]
News is: eBay tries now use shadow DOM/shadowRoot.

**Comment by BlazDT** [comment]
I saw the Reddit entry and therefore checked again, but no shadowroot for me.

**Comment by slavaleleka** [comment]
matching `first-line` pseudo-element will be possible in ExtendedCss v2
