### ISSUE TITLE
The rule doesn't work

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/ExtendedCss#171]
The rule:
`metager.org#results > div.result:has(> div.result-header > div.result-subheadline > a.result-link > span.advertisement-mark)`
doesn't work on:
https://metager.org/meta/meta.ger3?eingabe=Vpn&focus=web&m=en_US&mgv=d25fbe6a9a0979ffdc0ea56766ac4919

![schot](https://github.com/AdguardTeam/ExtendedCss/assets/18536328/429d989d-214b-4181-be1c-80c45fe04a1d)

**Comment by krystian3w** [comment]
In uBo looks as ad reinsertion and needed is CSS4 to force hide ads without use `:remove()`.
