### ISSUE TITLE
Extended CSS module does not protect the style attribute properly

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExtendedCss#21]
For example - 4pda.ru
http://4pda.ru/forum/index.php?showtopic=248165&st=400#entry54562922
when you click download:
while loadind
http://i82.fastpic.ru/big/2016/1111/f7/6101c4c4227ea87044971d8e6dafb7f7.png
after
http://i84.fastpic.ru/big/2016/1111/e4/e8824092e752760c420f716e094aa2e4.png
Temporary added:
```
4pda.ru#%#Object.defineProperty(window, 'MutationObserver', { get: function() { return {}; } });
```

**Comment by F4z** [comment]
I do not know if it is the same issue as on 4pda.ru, but I noticed a strange behavior with `[-ext-contains="something"]` in combination with `[style$="something"]`.
I wrote about this here - https://forum.adguard.com/index.php?threads/resolved-news-softpedia-com.12426/#post-100057
For example on this website - `http://www.w3schools.com/html/html_styles.asp`
with this rule:
`w3schools.com##[style$="blue;"][-ext-contains="I am blue"]`

I made video, so you can see what I mean as "strange behavior".
<details>
https://www.youtube.com/watch?v=N4uhkNnSKI8
</details>

**Comment by Alex-302** [comment]
Additional info for 4PDA - probably styles are removed by
```
(function() {
return function(mutations) {
            var i, mutation;
            for (i = 0; i < mutations.length; i++) {
                mutation = mutations[i];
                if (('attributes' == mutation.type) && ('style' == mutation.attributeName)) {
                    (!mutation.target.hasAttribute('style') || mutation.target.getAttribute('style').indexOf("none")>-1) && mutation.target.setAttribute('style','display:block!important');
                }
            }
        }

})
```

**Comment by ameshkov** [comment]
@F4z it seems there is a bug in ExtendedCss v1.06, thanks for alerting me!

Filed a separate bug report:
https://github.com/AdguardTeam/ExtendedCss/issues/22

**Comment by ameshkov** [comment]
@F4z false alarm, I'll elaborate in the forum thread:)

**Comment by ameshkov** [comment]
@Alex-302 while I am thinking about it, this rule will help you with 4pda:
```
4pda.ru#%#if (typeof MutationObserver !== 'undefined') { MutationObserver.prototype.observe = function() {}; MutationObserver.prototype.observe.toString = function() { return "function observe() { [native code] }"; } };
```

**Comment by F4z** [comment]
@ameshkov thank you for answer.
Ok, so I should not use `[style$="something"]` with `[-ext-contains="something"]` or with `[-ext-has="something"]`, but instead of `style$` I should use `style*`, yes?

**Comment by ameshkov** [comment]
The problem is solely in `style$`

**Comment by F4z** [comment]
Ok, thank you again, and sorry for this false alarm.

**Comment by Alex-302** [comment]
@ameshkov 
> @Alex-302 while I am thinking about it, this rule will help you with 4pda:

thanks, it works. Now I can change `display:block` attribute after page loading. But their script removes our style, and it is not re-applied.
Can we prevent removing on this site by JS?

**Comment by Mizzick** [comment]
Now we have a bug about this #24

**Comment by ameshkov** [comment]
Obsolete
