### ISSUE TITLE
Some matches-css rules are not applied

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/ExtendedCss#23]
```
Sizzle.tokenize("div:matches-css(background-image: url(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAAtCAMAAADMQ1gEAAACiFBMV…GvXb1P83yI+7SYdmNuSyrgbZqzbC/4V5IUTCpoQBV8zP9FOJzfMoGB/QAAAABJRU5ErkJggg==\"))")
```
throws an error.
```
Sizzle.tokenize("div:matches-css(\"background-image: url(\\\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAAtCAMAAADMQ1gEAAACiFBMV…GvXb1P83yI+7SYdmNuSyrgbZqzbC/4V5IUTCpoQBV8zP9FOJzfMoGB/QAAAABJRU5ErkJggg==\\\")\")");
```
works. Ideally the first selector should work too.

**Comment by seanl-adg** [comment]
Similar issue: https://forum.adguard.com/index.php?threads/resolved-wiadomosci-wp-pl.20408/#post-131171

The following are valid:
```
wiadomosci.wp.pl##div[class^="_"][-ext-matches-css="min-width: 300px"][-ext-matches-css="background-color: rgb(242, 242, 242)"]
wiadomosci.wp.pl##div[class^="_"][-ext-matches-css="background-color: 242, 242, 242"][-ext-matches-css="min-width: 300px"]
```
The following is invalid (`Sizzle.tokenize` throws)
```
wiadomosci.wp.pl##div[class^="_"][-ext-matches-css="background-color: rgb(242, 242, 242)"][-ext-matches-css="min-width: 300px"]
```

**Comment by seanl-adg** [comment]
The reason why such selectors are parsed as invalid is that, Sizzle selector engine does not assume that parentheses `()` can occur in a selector other than as a part of pseudo selectors.

Their regex for matching pseudo selectors:
```
	pseudos = ":(" + identifier + ")(?:\\((" +
		// To reduce the number of selectors needing tokenize in the preFilter, prefer arguments:
		// 1. quoted (capture 3; capture 4 or capture 5)
		"('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|" +
		// 2. simple (capture 6)
		"((?:\\\\.|[^\\\\()[\\]]|" + attributes + ")*)|" +
		// 3. anything else (capture 2)
		".*" +
		")\\)|)",
```

When no `()` are used inside the pseudo selector as in most cases, the content of the pseudo selector will be captured in `capture 6` and `capture 2`. However, in other cases, it will be captured in `capture 2` only. Such cases will results in messy matching results. For example, if `pseudos` is matched against `:has(.asdf:has(.fdsa)):has(.aaaa)` , the `capture 2` will be `.asdf:has(.fdsa)):has(.aaaa`, but the real content of the psuedo selector is only `.asdf:has(.fdsa)`. 

To remove garbage matched strings, they further processes the result with `preFilter` call:
```
	preFilter: {
		...
		"PSEUDO": function( match ) {
			var excess,
				unquoted = !match[6] && match[2];

			if ( matchExpr["CHILD"].test( match[0] ) ) {
				return null;
			}

			// Accept quoted arguments as-is
			if ( match[3] ) {
				match[2] = match[4] || match[5] || "";

			// Strip excess characters from unquoted arguments
			} else if ( unquoted && rpseudo.test( unquoted ) &&
				// Get excess from tokenize (recursively)
				(excess = tokenize( unquoted, true )) &&
				// advance to the next closing parenthesis
				(excess = unquoted.indexOf( ")", unquoted.length - excess ) - unquoted.length) ) {

				// excess is a negative index
				match[0] = match[0].slice( 0, excess );
				match[2] = unquoted.slice( 0, excess );
			}

			// Return only captures needed by the pseudo filter method (type and argument)
			return match.slice( 0, 3 );
		},
	...
	}

```

Here, if there is no `capture 6` (`!unquoted` is `false`), they check `rpseudo.test( unquoted )`, or in other words, whether the matched content contains a strings of a form of another pseudo selector. 

Since (it looks like) in all intended case of Sizzle selector engine parentheses occur as a part of pseudo selectors, I think it will result in true in any cases.

However, in our case of `background-image: rgb(....)`, it is not a form of pseudo selectors too, so `preFilter` will not further process the result and the selector parser will use the result containing garbage as a content of `matched-css(..)`. 


One way to fix it would be to use quotes, like `:matches-css("background-color:...")`

To use unquoted contents in `:matches-css` too, one way is to modify `preFilter.PSEUDO`, so that it processes matched results in a different way when the name of the pseudo selector is `matches-css`.

**Comment by ameshkov** [comment]
Possible solution:
`matches-css(attr: string)` -- for backwards compatibility (escaping `():` would be mandatory)
`matches-css(attr: /regex/)` -- regex support

**Comment by ameshkov** [comment]
A possible general rule for parsing it:
> pseudo class argument ends with the first bracket found save for two special cases (`url` and `rgb`)
> btw it does not stop us from adding escape support

**Comment by seanl-adg** [comment]
> escaping `():` would be mandatory
Escaping `:` won't be needed.

**Comment by seanl-adg** [comment]
Now
```
new ExtendedCss("div:matches-css(background-image: url(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAAtCAMAAADMQ1gEAAACiFBMV…GvXb1P83yI+7SYdmNuSyrgbZqzbC/4V5IUTCpoQBV8zP9FOJzfMoGB/QAAAABJRU5ErkJggg==\")){display:none!important;}")
```
throws, but 
```
new ExtendedCss("div:matches-css(background-image: url\\\(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAAtCAMAAADMQ1gEAAACiFBMV…GvXb1P83yI+7SYdmNuSyrgbZqzbC/4V5IUTCpoQBV8zP9FOJzfMoGB/QAAAABJRU5ErkJggg==\"\\\)){display:none!important;}")
```
does not.
