### ISSUE TITLE
4pda.ru - extended CSS rule leads to hang a tab[broeser extension]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExtendedCss#24]
Steps to reproduce:
- add any extended CSS rule to extension. For exaple:
```
4pda.ru##.fix-post > article.post div.visual[-ext-has='a[title="War Thunder"]']
```
- refresh the tab.

**Comment by Mizzick** [comment]
There is mutation observer in page script:
`u[4] = function() {
            return function(b) {
                return function(l) {
                    var a, c;
                    for (a = 0; a < l.length; a++)
                        c = l[a],
                        "attributes" == c.type && "style" == c.attributeName && (c = c.target,
                        b[8].call(c, "style") && b[7].call(c, "style"))
                }
            }
        }("jjEncode", 'window["_o0"]'),`
that is in conflict with ours one in ExtendedCss protectionFunction.

**Comment by ameshkov** [comment]
We have several options

1. Apply style to the element using it's CSS path (just like we hide iframes).
2. Apply style to the shadow element (need to do a research).

In any case we should change `protectionFunction` to protect from infinite loops.

**Comment by ameshkov** [comment]
Obsolete
