### ISSUE TITLE
Support [-abp-*] syntax

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/ExtendedCss#30]
ABP is introducing backward-compatible syntaxes `[-abp-has` and `[-abp-has-text`.
https://issues.adblockplus.org/ticket/3143
https://issues.adblockplus.org/ticket/5249
We need to convert them into `:has` and `:contains` respectively.

**Comment by ameshkov** [comment]
`-abp` should be just an alias for our existing `-ext`

**Comment by ameshkov** [comment]
@seanl-adg I've been thinking about it lately and after all, I suppose we should support this syntax natively (talking about `:-abp-has()`).

It's not hard to do, and it'd be easier for people to import external filter lists which use that syntax.

Here is what should be done:

1. Support `:-abp-has()` as a synonym to `has`
2. Release an updated 1.0.8 version
3. Update product-specific issues about upgrading ExtCss -- add information about parsing `#?#` and `:-abp-has`

**Comment by seanl-adg** [comment]
They changed their syntax to `-abp-contains` instead of `-abp-has-text`
