### ISSUE TITLE
Support ":scope"

### ISSUE THREAD

**Issue by F4z** [AdguardTeam/ExtendedCss#31]
I see that you want add support for `[-abp-*]` syntax and `:has-text()` , so maybe you can also add support for `:scope` which is supported by uBlock Origin or is not needed/necessary?

In `uBlock filter` are few rules which use this, for example - https://github.com/uBlockOrigin/uAssets/blob/e4e4d64e33615ffd95cd7524d54f513e888e4950/filters/filters.txt#L1128

`nextinpact.com###list_news > section[class]:if(:scope > span:has-text(Publicité))`

**Edit (by @ameshkov):**  `:scope` description -- https://developer.mozilla.org/en-US/docs/Web/CSS/:scope

**Comment by ameshkov** [comment]
This exact rule can be easily rewritten in AG current syntax:
```
nextinpact.com###list_news > section[class]:has(>span:contains(Publicité))
```

**Comment by F4z** [comment]
Ok, I see this now, so `:has( > [...])` in Adguard is the same as `:has(:scope > [...])` in uBlock.

Thank you for your answer.

**Comment by ameshkov** [comment]
I thought uBO also supports it as `:has(> )` syntax is from RFC. Shouldn't it work in uBO as well?

**Comment by ameshkov** [comment]
Here is a detailed description:
https://developer.mozilla.org/en-US/docs/Web/CSS/:has

**Comment by F4z** [comment]
No, I tried this rule - `wp.pl##div[class]:has(> img[src*=".wp.pl"])` - here - http://tech.wp.pl/
and it works in Adguard, but not in uBO.

This works in uBO - `wp.pl##div[class]:has(:scope > img[src*=".wp.pl"])`

This rule hides ads lefovers/placeholders marked on screenshot below.
<details><summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/26201272/77d2249a-3bd2-11e7-9582-90c165c98a39.png)
</details>
<br>

I know, there is an easier way, to hide it, but it was only for test purpose.

**Comment by ameshkov** [comment]
I guess it makes sense to add `:scope` support anyway: https://developer.mozilla.org/en-US/docs/Web/CSS/:scope

**Comment by ameshkov** [comment]
Meanwhile, do mentions work here?

@gorhill, could you please consider adding RFC-based syntax to `:has` implementation? `:has(:scope > selector)` --> `:has(> selector)`

**Comment by gorhill** [comment]
Yes I should. I suppose it's just a matter of prepending `:scope ` internally to whatever selector is inside `:has(...)`?

**Comment by ameshkov** [comment]
@gorhill yeah, exactly

**Comment by seanl-adg** [comment]
The original proposed usage has a workaround, and the usage mentioned in https://github.com/AdguardTeam/ExtendedCss/issues/31#issuecomment-302390906 is deprecated in both Firefox<sup>1</sup> and Chrome<sup>2</sup>, so I'd like to mark this issue as "wontfix".

<sup>[1]</sup> https://bugzilla.mozilla.org/show_bug.cgi?id=1291515
<sup>[2]</sup> https://www.chromestatus.com/feature/5374137958662144
