### ISSUE TITLE
Compatibility with old versions Internet Explorer

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#35]
Look for a way to run unit tests on older versions of IE.

We can simply ask @AdguardTeam/qa-team to assist with testing, but to make their life easier, we need an instruction on how to do it.

As I see it, the easiest way would be to have a `gh-pages` branch here so that they could run unit-tests simply by opening a page.

**Comment by TPS** [comment]
If y'all are ___very___ serious about testing in-house, there are 2 MS-approved VM solutions:
- [cloud-based](https://developer.microsoft.com/en-us/microsoft-edge/tools/remote/)
-  [downloadable](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)

**Comment by ameshkov** [comment]
@TPS downloadable is what we have, cloud-based -- not really necessary

**Comment by ameshkov** [comment]
@AdguardTeam/qa-team guys please assist.

Here is a link you should use to test ExtendedCss:
https://adguardteam.github.io/ExtendedCss/index.html

Run the tests in every major browser and also in IE9 and IE10.

**Comment by ameshkov** [comment]
@AdguardTeam/qa-team ?

**Comment by zebrum** [comment]
Microsoft Edge 40.15063.0.0 - passed

Google chrome 59.0.3071.115  - passed

Firefox 54.0.1 - passed

Pale moon  27.3.0 - passed

IE 11.413.15063.0 - passed

Opera 46.0.2597.32 - passed

IE9.0.8112.16421: Extended Css - test attribute protection failed 
<details>

![screenshot 2017-07-04 14 19 10](https://user-images.githubusercontent.com/23637588/27829191-ee5f0fae-60c8-11e7-833f-204a238e8a72.png)

</details>

IE 10.0.9200.16438: Extended Css - test attribute protection failed 

<details>

![screenshot 2017-07-04 15 06 04](https://user-images.githubusercontent.com/23637588/27829468-6e8d485c-60ca-11e7-8228-755e8f10e58e.png)


</details>

**Comment by zebrum** [comment]
in IE9.0.8112.16421 6,7 tests fails in extended css section:

<details>

![screenshot 2017-07-06 19 37 51](https://user-images.githubusercontent.com/23637588/27922264-1ffb5070-6283-11e7-8444-f6190329c61f.png)


</details>
