### ISSUE TITLE
Prepare a bookmarklet for testing ExtCss selectors

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#36]
We sometimes need an easy way to debug ExtCss selectors.

I suggest creating a simple bookmarklet that will load ExtCss to the page and expose a function that could be used from the browser console to test selectors.

For instance, here is a script that loads ExtCss:
```
(function() {
	var script = document.createElement('script');
	script.setAttribute('src', 'https://ameshkov.github.io/web/extended-css-1.0.6.js');
	document.documentElement.appendChild(script);
	script.addEventListener('load', function() {
		alert('ExtCss loaded successfully');
	});
})();
```

Note, that I used Github pages to serve ExtCss distro.

**Comment by ameshkov** [comment]
The other option would be to prepare a dev-tools extension.

Here is how to do it:
https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/browser/chrome/lib/devtools.js
https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/browser/chrome/lib/pages/devtools-elements-sidebar.js

**Comment by seanl-adg** [comment]
sticking to providing a js snippet
