### ISSUE TITLE
Incorrect parsing of styles

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/ExtendedCss#57]
#### Steps to reproduce:
`(new ExtendedCss(':contains(/[\\w]{9,}/) { display:none!important; }')).apply()`

#### Expected:
No error is printed in the console.

#### Actual:
```
Extended selector is invalid: /)
Extended selector is invalid: :contains(/[\w]
```

**Comment by ameshkov** [comment]
Let's change the interface of ExtendedCss, let it accept a list of selectors instead of the current interface.
