### ISSUE TITLE
Add a detailed description of the extended pseudo-classes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#68]
Explain every pseudo-class using the same layout as here:
https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/pages/02.general/02.how-to-create-your-own-ad-filters/docs.en.md#extended-css-has

* `:has` (`:-abp-has`, `:if`)
* `:if-not`
* `:contains` (`:-abp-contains`, `:has-text`, `:-abp-has-text`)
* `:matches-css`, `:matches-css-before`, `:matches-css-after`
* `:properties` (`:-abp-properties`)
* `{ debug: true }` and `{ debug: global }`

@seanl-adg how would you describe the difference between `:properties` and `:matches-css` so that filters maintainers understand it easier?

**Comment by seanl-adg** [comment]
![scrs](https://user-images.githubusercontent.com/22858651/37627047-f97c6bfc-2c15-11e8-87f6-8dd0f22f88c2.png)

In short, `:matches-css` is about "Computed" tab and `:properties` is about "Styles" tab.

Detailed description must include how cross-origin stylesheets are treated and what is a 'canonical string form'.

**Comment by ameshkov** [comment]
> 'canonical string form'.

Elaborate on this plz, canonical string form of what?

**Comment by seanl-adg** [comment]
of a CSS rule, it's just a tentative name for what [`stringifyRule`](https://github.com/AdguardTeam/ExtendedCss/blob/master/lib/style-observer.js#L312) returns.
