### ISSUE TITLE
A couple of issues with the master branch

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/ExtendedCss#69]
1. Debugging and global debugging is broken with updated `ExtendedSelector` interface.
2. An error occurs during `ExtendedCss.query` call, it turns out that we did not assume that `StyleObserver.clear` can be called in an un-initialized state.

**Comment by ameshkov** [comment]
Not fully resolved, change selectors order in the "Test global debugging" to see what's the problem
