### ISSUE TITLE
HTML comments are ignored

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExtendedCss#73]
Site: https://pikabu.ru/
AdGuard extension 2.10.8
Chrome
The rule:
`pikabu.ru##.stories-feed__container > article.story:has(.story__main:contains(Яндекс))`
![image](https://user-images.githubusercontent.com/8361299/45817672-2db3e900-bce8-11e8-931e-3c899c0445be.png)
It works only when `:contains(.)`

**Comment by ameshkov** [comment]
HTML comments are ignored..

**Comment by ameshkov** [comment]
This is just how it works, we may solve this by some scriptlet or we may need to introduce a different pseudo
