### ISSUE TITLE
`:properties()` is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExtendedCss#74]
For example:
`i.ua##div[class="logo_container"]:properties(margin-bottom: 16px)`

<details>

![image](https://user-images.githubusercontent.com/8361299/48134018-55afd980-e2a1-11e8-9e70-34c7bb59a4d1.png)

</details>

**Comment by ameshkov** [comment]
The problem is that the stylesheet is loaded from `i3.i.ua` and browser considers it a cross-domain origin -> prohibits access to its rules
