### ISSUE TITLE
Failed to build filters

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExtendedCss#75]
Travis failed to build filters, because of `hufilter` rules:
```
prohardver.hu##p:-abp-contains(Amikor a szoftver illeszkedik a meglévő üzleti folyamatokhoz.)
prohardver.hu##div[id="center"] > div:-abp-has(div):-abp-has(a):-abp-has(Mostantól bármely bank ügyfelének elérhető a mobilfizetés élménye.)
```
Excluded https://github.com/AdguardTeam/FiltersRegistry/pull/123

**Comment by maximtop** [comment]
Issue moved to [AdguardTeam/FiltersCompiler #31](https://github.com/AdguardTeam/FiltersCompiler/issues/31) via [**ZenHub**](https://www.zenhub.com/)
