### ISSUE TITLE
Extended CSS rules aren't re-evaluated on attribute change

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#77]
Here is the test case:
http://ameshkov.github.io/web/watchattr.html

Here is the relevant discussion:
https://github.com/uBlockOrigin/uBlock-issues/issues/341

Important comments there:
* https://github.com/uBlockOrigin/uBlock-issues/issues/341#issuecomment-449858461
* https://github.com/uBlockOrigin/uBlock-issues/issues/341#issuecomment-449860631

**Comment by krystian3w** [comment]
Maybe same bug: `4kdownload.com`

```
4kdownload.com##body[style^="padding-right"]:has(.remodal-wrapper:has(#ouibounce-modal.is-opened)) .remodal-overlay
```

I try remove overlay activated only by pop-up newsletter. No if pop-up has video promotion from vimeo.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/ExtendedCss/issues/122 https://github.com/ameshkov/web/pull/2

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/18147

**Comment by ameshkov** [comment]
@zzebrum I've already opened a new one: https://github.com/AdguardTeam/ExtendedCss/issues/122
