### ISSUE TITLE
Add ability to remove matched elements

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExtendedCss#79]
### Selectors removal mode

Sometimes, it is necessary to remove a matching element instead of hiding it or applying custom styles. In order to do it, you can use a special style property: `remove`.

#### Example
```
.banner { remove: true; }
```

> Please note, that other style properties will be ignored if `remove` is specified.

**Comment by maximtop** [comment]
Better selector would be `example.org##div:has(> ad) { remove: true }`

**Comment by ameshkov** [comment]
@maximtop I've updated the issue text

**Comment by Alex-302** [comment]
`example.org#$#div:has(> h1) { remove: true; }`
this rule works, but is not displayed in the filtering log.

example.org#$#div> h1 { remove: true; }
this rule has no ExtCSS attribute, but displayed as applied(element is not changed or removed).

<details>

![image]()
![image](https://user-images.githubusercontent.com/8361299/53747308-a4662c80-3eab-11e9-9e5f-03f8cfededeb.png)

</details>

**Comment by ameshkov** [comment]
> example.org#$#div> h1 { remove: true; }
> this rule has no ExtCSS attribute, but displayed as applied(element is not changed or removed).

This is not a bug. Use `#?$#`

**Comment by ameshkov** [comment]
The first one is a bug.

**Comment by Alex-302** [comment]
> This is not a bug. Use `#?$#`.

got it

**Comment by maximtop** [comment]
the marker above is incorrect
use this marker `#$?#`

**Comment by ameshkov** [comment]
Ops my bad:)
