### ISSUE TITLE
Extended css causes performance issues

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/ExtendedCss#83]
Scroll on the page https://4pda.ru/2019/03/02/356226/ doesn't works smoothly.

Was found that this rule
`4pda.ru##body > :not(td):not([id="ipbwrapper"]) > :not(td) > div > div+:not(td):matches-css(height: /|90\.\d\d\d/)`

causes such performance issues

**Comment by Alex-302** [comment]
Another example(not reproduced on my end) - scrolling is not smooth:
https://pikabu.ru/
Performance profile from Chrome dev tools:
https://yadi.sk/d/bSUlglkYbV634g
