### ISSUE TITLE
Add :xpath support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#86]
See the example here:
https://github.com/AdguardTeam/Scriptlets/issues/29

* [x] Add :xpath support
* [x] Change filters compiler so that it was not excluding :xpath rules
* [x] Change validation rules in the BrowserExtension, Safari, CoreLibs
* [x] Add :xpath documention to KB

**Comment by krystian3w** [comment]
If dom tree is unique possible cover text with `::before` / `::after` pseudoelements: https://github.com/AdguardTeam/AdguardFilters/commit/f665ef30e5c9aead742ac18d2e5c4e6bd232d809
