### ISSUE TITLE
turksemedia.nl - cannot hide element using Extended CSS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ExtendedCss#87]
URL: https://turksemedia.nl/wk-handboogschieten-in-nederland-turkije-pakt-zilver/

Screenshot:

<details>

![image](https://user-images.githubusercontent.com/8361299/59679502-af816600-91d7-11e9-8103-45ca041d2a37.png)

</details>

The rule:
```
turksemedia.nl##div[class="sidebar_item"][style="padding-bottom: 16px;"]:has(> a > img[width="276"])
```

### Actual behavior:

After blinking banners are visible.

But this rule works fine:
`turksemedia.nl#$?#div[class="sidebar_item"][style="padding-bottom: 16px;"]:has(> a > img[width="276"]) { remove: true; }`

Before checking add exclusion rule:
`turksemedia.nl#@$?#div[class="sidebar_item"][style="padding-bottom: 16px;"]:has(> a > img[width="276"]) { remove: true; }`

AdGuard 3.1.3, Chrome.

**Comment by AdamWr** [comment]
I'm not sure, but I guess that it's due to `[style="padding-bottom: 16px;"]` and probably changing it to `[style*="padding-bottom: 16px;"]` should works.

https://forum.adguard.com/index.php?threads/resolved-news-softpedia-com.12426/#post-112475

**Comment by Alex-302** [comment]
Sometimes that rule works, somtimes - no.
