### ISSUE TITLE
Provide a way to disable

### ISSUE THREAD

**Issue by optomux** [AdguardTeam/ExtendedCss#88]
Provide a way to disable js and or css injection globally.
Slows down browsing significantly.

/** content-script - v1.1.4 - 14/05/2019 */

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1007](https://github.com/AdguardTeam/CoreLibs/issues/1007) via [**ZenHub**](https://www.zenhub.com/)
