### ISSUE TITLE
Remove :properties pseudo-class support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#93]
It is now removed from ABP, and we never used it in AdGuard filters:
https://github.com/AdguardTeam/ExtendedCss#extended-css-properties

It should be also removed from KB:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#extended-css-properties

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/448
