### ISSUE TITLE
Can not hide element with 'xlink:href'

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/ExtendedCss#99]
### Steps to reproduce:
1. Add this rule:
`mdn.mozillademos.org#?#a[*|href="https://developer.mozilla.org/"]`
2. Go here - https://mdn.mozillademos.org/en-US/docs/Web/SVG/Attribute/xlink:href$samples/topExample

### Expected behavior

Link should be hidden.

### Actual behavior

Rule doesn't work.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/73480599-77134e80-439a-11ea-90a1-47ff14a6f47d.png)

</details>

<hr>

This rule works fine:
`mdn.mozillademos.org##a[*|href="https://developer.mozilla.org/"]`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/73480883-ff91ef00-439a-11ea-8e53-8777617796e9.png)

</details>

**Comment by slavaleleka** [comment]
Sizzle does not support Namespaces (and [does not planning to fix it](https://github.com/jquery/sizzle/issues/69#issuecomment-3620438))

**Comment by ameshkov** [comment]
We should get back to this task when we replace Sizzle

**Comment by slavaleleka** [comment]
merged into https://github.com/AdguardTeam/ExtendedCss/issues/110

**Comment by slavaleleka** [comment]
since [`xlink:href` is depracated](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) we decided not to support such cases while ditching Sizzle
